name: user_repository
description: A repository contain all client helper
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  api_client:
    path: ../api_client
  equatable: ^2.0.3
  flutter_launcher_icons: ^0.10.0
  gateway_client:
    path: ../gateway_client
  json_annotation: ^4.6.0
  json_serializable: ^6.3.1
  rxdart: ^0.27.5
  secure_storage_client:
    path: ../secure_storage_client
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
