name: bee
description: An flutter app that helps manage IoT device used MQTT protocol
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  api_client:
    path: ./packages/api_client
  awesome_snackbar_content: ^0.0.8
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  day_night_time_picker: ^1.1.2
  equatable: ^2.0.3
  firebase_core: ^1.21.1
  firebase_messaging: ^13.0.0
  fl_chart: ^0.55.1
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_gen: ^4.3.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.7
  flutter_secure_storage: ^5.1.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.1.3
  gateway_client:
    path: ./packages/gateway_client
  intl: ^0.17.0
  loader_overlay: ^2.0.10
  modal_bottom_sheet: ^2.1.0
  onesignal_flutter: ^3.4.1
  rfc_6901: ^0.1.1
  secure_storage_client:
    path: ./packages/secure_storage_client
  syncfusion_flutter_datepicker: ^20.2.46
  url_launcher: ^6.1.5
  user_repository:
    path: ./packages/user_repository
  uuid: ^3.0.6

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.2.0
  flutter_gen_runner: ^4.3.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter_gen:
  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/colors/colors.xml

flutter_icons:
  image_path: "assets/icons/logo.png"
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/icons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          weight: 900
