// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMt3x3fo91Eu-u8Lqt0_BXT22T2ozKoTo',
    appId: '1:441892589835:web:727128b27f5169936e920e',
    messagingSenderId: '441892589835',
    projectId: 'bee1903',
    authDomain: 'bee1903.firebaseapp.com',
    storageBucket: 'bee1903.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEdjGQu5dOVwNDWGCFwJgLMHMq0aUhh74',
    appId: '1:441892589835:android:97b5ba3c8d2b7e7e6e920e',
    messagingSenderId: '441892589835',
    projectId: 'bee1903',
    storageBucket: 'bee1903.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCx2bezdjNzDgsjhqU0wQeYabz-pQ3Iq8',
    appId: '1:441892589835:ios:d233fea5942298006e920e',
    messagingSenderId: '441892589835',
    projectId: 'bee1903',
    storageBucket: 'bee1903.appspot.com',
    iosClientId: '441892589835-luurr0r6dqat9usoh1ca5u5kfpikfnjf.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.bee',
  );
}
